from io import StringIO
from collections import OrderedDict
import requests
from bs4 import BeautifulSoup
import json
import re
import os
import spacy


SUPPLEMENTS = [
    "https://examine.com/supplements/1-3-dimethylamylamine/",
    "https://examine.com/supplements/2-4-dinitrophenol/",
    "https://examine.com/supplements/5-htp/",
    "https://examine.com/supplements/7-8-dihydroxyflavone/",
    "https://examine.com/supplements/7-keto-dhea/",
    "https://examine.com/supplements/acorus-calamus/",
    "https://examine.com/supplements/adrafinil/",
    "https://examine.com/supplements/aframomum-melegueta/",
    "https://examine.com/supplements/agmatine/",
    "https://examine.com/supplements/alanine/",
    "https://examine.com/supplements/alanylglutamine/",
    "https://examine.com/supplements/alcohol/",
    "https://examine.com/supplements/aloe-vera/",
    "https://examine.com/supplements/alpha-gpc/",
    "https://examine.com/supplements/alpha-lipoic-acid/",
    "https://examine.com/supplements/amaranth/",
    "https://examine.com/supplements/anacyclus-pyrethrum/",
    "https://examine.com/supplements/anatabine/",
    "https://examine.com/supplements/andrographis-paniculata/",
    "https://examine.com/supplements/anethum-graveolens/",
    "https://examine.com/supplements/angelica-gigas/",
    "https://examine.com/supplements/aniracetam/",
    "https://examine.com/supplements/apigenin/",
    "https://examine.com/supplements/apocynum-venetum/",
    "https://examine.com/supplements/arachidonic-acid/",
    "https://examine.com/supplements/arginine/",
    "https://examine.com/supplements/aromatherapy/",
    "https://examine.com/supplements/aronia-melanocarpa/",
    "https://examine.com/supplements/artemisia-iwayomogi/",
    "https://examine.com/supplements/artichoke-extract/",
    "https://examine.com/supplements/ascophyllum-nodosum/",
    "https://examine.com/supplements/ashwagandha/",
    "https://examine.com/supplements/asparagus-racemosus/",
    "https://examine.com/supplements/astaxanthin/",
    "https://examine.com/supplements/asteracantha-longifolia/",
    "https://examine.com/supplements/astragalus-membranaceus/",
    "https://examine.com/supplements/ayurveda/",
    "https://examine.com/supplements/bacopa-monnieri/",
    "https://examine.com/supplements/banaba-leaf/",
    "https://examine.com/supplements/basella-alba/",
    "https://examine.com/supplements/beet-root/",
    "https://examine.com/supplements/benfotiamine/",
    "https://examine.com/supplements/berberine/",
    "https://examine.com/supplements/beta-alanine/",
    "https://examine.com/supplements/betalains/",
    "https://examine.com/supplements/biotin/",
    "https://examine.com/supplements/black-cohosh/",
    "https://examine.com/supplements/black-pepper/",
    "https://examine.com/supplements/bladderwrack/",
    "https://examine.com/supplements/blueberry/",
    "https://examine.com/supplements/boerhaavia-diffusa/",
    "https://examine.com/supplements/boron/",
    "https://examine.com/supplements/boswellia-serrata/",
    "https://examine.com/supplements/bpc-157/",
    "https://examine.com/supplements/branched-chain-amino-acids/",
    "https://examine.com/supplements/brassaiopsis-glomerulata/",
    "https://examine.com/supplements/brassica-vegetables/",
    "https://examine.com/supplements/brassinosteroids/",
    "https://examine.com/supplements/bromelain/",
    "https://examine.com/supplements/bryonia-laciniosa/",
    "https://examine.com/supplements/bulbine-natalensis/",
    "https://examine.com/supplements/butea-monosperma/",
    "https://examine.com/supplements/butea-superba/",
    "https://examine.com/supplements/caesalpinia-benthamiana/",
    "https://examine.com/supplements/caffeine/",
    "https://examine.com/supplements/calcium-d-glucarate/",
    "https://examine.com/supplements/calcium/",
    "https://examine.com/supplements/capsaicin/",
    "https://examine.com/supplements/capsicum-carotenoids/",
    "https://examine.com/supplements/caralluma-fimbriata/",
    "https://examine.com/supplements/casein-protein/",
    "https://examine.com/supplements/cbd/",
    "https://examine.com/supplements/cdp-choline/",
    "https://examine.com/supplements/celastrus-paniculatus/",
    "https://examine.com/supplements/celery-seed-extract/",
    "https://examine.com/supplements/centella-asiatica/",
    "https://examine.com/supplements/centrophenoxine/",
    "https://examine.com/supplements/chlorella/",
    "https://examine.com/supplements/chlorogenic-acid/",
    "https://examine.com/supplements/chlorophytum-borivilianum/",
    "https://examine.com/supplements/choline/",
    "https://examine.com/supplements/chondroitin/",
    "https://examine.com/supplements/chromium/",
    "https://examine.com/supplements/chrysin/",
    "https://examine.com/supplements/cinnamon/",
    "https://examine.com/supplements/cissus-quadrangularis/",
    "https://examine.com/supplements/citric-acid/",
    "https://examine.com/supplements/citrulline/",
    "https://examine.com/supplements/citrullus-colocynthis/",
    "https://examine.com/supplements/clenbuterol/",
    "https://examine.com/supplements/clitoria-ternatea/",
    "https://examine.com/supplements/clubmoss/",
    "https://examine.com/supplements/cnidium-monnieri/",
    "https://examine.com/supplements/cocoa-extract/",
    "https://examine.com/supplements/coconut-oil/",
    "https://examine.com/supplements/codonopsis-pilosula/",
    "https://examine.com/supplements/coenzyme-q10/",
    "https://examine.com/supplements/coffee/",
    "https://examine.com/supplements/cold-exposure/",
    "https://examine.com/supplements/coleus-forskohlii/",
    "https://examine.com/supplements/colostrum/",
    "https://examine.com/supplements/coluracetam/",
    "https://examine.com/supplements/conjugated-linoleic-acid/",
    "https://examine.com/supplements/convolvulus-pluricaulis/",
    "https://examine.com/supplements/copper/",
    "https://examine.com/supplements/cordyceps/",
    "https://examine.com/supplements/crataegus-pinnatifida/",
    "https://examine.com/supplements/creatine/",
    "https://examine.com/supplements/creatinol-o-phosphate/",
    "https://examine.com/supplements/cucurbita-pepo/",
    "https://examine.com/supplements/curcumin/",
    "https://examine.com/supplements/cyanidin/",
    "https://examine.com/supplements/d-aspartic-acid/",
    "https://examine.com/supplements/d-ribose/",
    "https://examine.com/supplements/d-serine/",
    "https://examine.com/supplements/dactylorhiza-hatagirea/",
    "https://examine.com/supplements/damiana-leaf/",
    "https://examine.com/supplements/dark-therapy/",
    "https://examine.com/supplements/dehydroepiandrosterone/",
    "https://examine.com/supplements/dendrobium/",
    "https://examine.com/supplements/diindolylmethane/",
    "https://examine.com/supplements/dimocarpus-longan/",
    "https://examine.com/supplements/dioscorea-villosa/",
    "https://examine.com/supplements/dmae/",
    "https://examine.com/supplements/eca/",
    "https://examine.com/supplements/ecdysteroids/",
    "https://examine.com/supplements/echinacea/",
    "https://examine.com/supplements/ecklonia-cava/",
    "https://examine.com/supplements/eclipta-alba/",
    "https://examine.com/supplements/egg-chicken/",
    "https://examine.com/supplements/eleutherococcus-senticosus/",
    "https://examine.com/supplements/emblica-officinalis/",
    "https://examine.com/supplements/energy-drinks/",
    "https://examine.com/supplements/ephedrine/",
    "https://examine.com/supplements/eriobotrya-japonica/",
    "https://examine.com/supplements/eschscholzia-californica/",
    "https://examine.com/supplements/eucommia-ulmoides/",
    "https://examine.com/supplements/euonymus-alatus/",
    "https://examine.com/supplements/eurycoma-longifolia-jack/",
    "https://examine.com/supplements/evodia-rutaecarpa/",
    "https://examine.com/supplements/evolvulus-alsinoides/",
    "https://examine.com/supplements/fadogia-agrestis/",
    "https://examine.com/supplements/fennel-essential-oil/",
    "https://examine.com/supplements/fenugreek/",
    "https://examine.com/supplements/ferula-asafoetida/",
    "https://examine.com/supplements/feverfew/",
    "https://examine.com/supplements/fish-oil/",
    "https://examine.com/supplements/folic-acid/",
    "https://examine.com/supplements/fucoxanthin/",
    "https://examine.com/supplements/gaba/",
    "https://examine.com/supplements/gamma-oryzanol/",
    "https://examine.com/supplements/ganoderma-lucidum/",
    "https://examine.com/supplements/garcinia-cambogia/",
    "https://examine.com/supplements/garlic/",
    "https://examine.com/supplements/ginger/",
    "https://examine.com/supplements/ginkgo-biloba/",
    "https://examine.com/supplements/glucosamine/",
    "https://examine.com/supplements/glucuronolactone/",
    "https://examine.com/supplements/glutamine/",
    "https://examine.com/supplements/glutathione/",
    "https://examine.com/supplements/gluten/",
    "https://examine.com/supplements/glycine/",
    "https://examine.com/supplements/grape-seed-extract/",
    "https://examine.com/supplements/grapefruit/",
    "https://examine.com/supplements/green-coffee-extract/",
    "https://examine.com/supplements/green-tea-catechins/",
    "https://examine.com/supplements/griffonia-simplicifolia/",
    "https://examine.com/supplements/guggul/",
    "https://examine.com/supplements/gynostemma-pentaphyllum/",
    "https://examine.com/supplements/harpagophytum-procumbens/",
    "https://examine.com/supplements/hederagenin/",
    "https://examine.com/supplements/hemp-protein/",
    "https://examine.com/supplements/hesperidin/",
    "https://examine.com/supplements/hibiscus-macranthus/",
    "https://examine.com/supplements/hibiscus-rosasinensis/",
    "https://examine.com/supplements/hibiscus-sabdariffa/",
    "https://examine.com/supplements/higenamine/",
    "https://examine.com/supplements/hmb/",
    "https://examine.com/supplements/holy-basil/",
    "https://examine.com/supplements/hoodia-gordonii/",
    "https://examine.com/supplements/hordenine/",
    "https://examine.com/supplements/horny-goat-weed/",
    "https://examine.com/supplements/horse-chestnut/",
    "https://examine.com/supplements/hovenia-dulcis/",
    "https://examine.com/supplements/huperzine-a/",
    "https://examine.com/supplements/hypericum-perforatum/",
    "https://examine.com/supplements/idebenone/",
    "https://examine.com/supplements/inositol/",
    "https://examine.com/supplements/iodine/",
    "https://examine.com/supplements/iron/",
    "https://examine.com/supplements/irvingia-gabonensis/",
    "https://examine.com/supplements/isoleucine/",
    "https://examine.com/supplements/japanese-knotweed/",
    "https://examine.com/supplements/juniperus-chinensis/",
    "https://examine.com/supplements/kaempferia-parviflora/",
    "https://examine.com/supplements/kaempferol/",
    "https://examine.com/supplements/kava/",
    "https://examine.com/supplements/keto/",
    "https://examine.com/supplements/king-oyster/",
    "https://examine.com/supplements/kombucha/",
    "https://examine.com/supplements/krill-oil/",
    "https://examine.com/supplements/l-carnitine/",
    "https://examine.com/supplements/l-dopa/",
    "https://examine.com/supplements/l-threonate/",
    "https://examine.com/supplements/l-tyrosine/",
    "https://examine.com/supplements/lactobacillus-casei/",
    "https://examine.com/supplements/lactobacillus-reuteri/",
    "https://examine.com/supplements/lavender/",
    "https://examine.com/supplements/leucic-acid/",
    "https://examine.com/supplements/leucine/",
    "https://examine.com/supplements/licorice/",
    "https://examine.com/supplements/light-therapy/",
    "https://examine.com/supplements/limonene/",
    "https://examine.com/supplements/lutein/",
    "https://examine.com/supplements/lysine/",
    "https://examine.com/supplements/maca/",
    "https://examine.com/supplements/magnesium/",
    "https://examine.com/supplements/magnolia-officinalis/",
    "https://examine.com/supplements/manganese/",
    "https://examine.com/supplements/mangifera-indica/",
    "https://examine.com/supplements/marijuana/",
    "https://examine.com/supplements/massularia-acuminata/",
    "https://examine.com/supplements/mcts/",
    "https://examine.com/supplements/melatonin/",
    "https://examine.com/supplements/melissa-officinalis/",
    "https://examine.com/supplements/methylsulfonylmethane/",
    "https://examine.com/supplements/microlactin/",
    "https://examine.com/supplements/milk-protein/",
    "https://examine.com/supplements/milk-thistle/",
    "https://examine.com/supplements/minoxidil/",
    "https://examine.com/supplements/mitoq/",
    "https://examine.com/supplements/modafinil/",
    "https://examine.com/supplements/molybdenum/",
    "https://examine.com/supplements/moringa-oleifera/",
    "https://examine.com/supplements/morus-alba/",
    "https://examine.com/supplements/mucuna-pruriens/",
    "https://examine.com/supplements/muira-puama/",
    "https://examine.com/supplements/music/",
    "https://examine.com/supplements/myricetin/",
    "https://examine.com/supplements/n-acetylcysteine/",
    "https://examine.com/supplements/nardostachys-jatamansi/",
    "https://examine.com/supplements/nattokinase/",
    "https://examine.com/supplements/nefiracetam/",
    "https://examine.com/supplements/nelumbo-nucifera/",
    "https://examine.com/supplements/nicotine/",
    "https://examine.com/supplements/nigella-sativa/",
    "https://examine.com/supplements/nitrate/",
    "https://examine.com/supplements/noopept/",
    "https://examine.com/supplements/nutmeg/",
    "https://examine.com/supplements/octopamine/",
    "https://examine.com/supplements/oleamide/",
    "https://examine.com/supplements/oleoylethanolamide/",
    "https://examine.com/supplements/olive-leaf-extract/",
    "https://examine.com/supplements/olive-oil/",
    "https://examine.com/supplements/ophiopogon-japonicus/",
    "https://examine.com/supplements/origanum-vulgare/",
    "https://examine.com/supplements/ornithine/",
    "https://examine.com/supplements/orthosiphon-stamineus/",
    "https://examine.com/supplements/oxaloacetate/",
    "https://examine.com/supplements/oxiracetam/",
    "https://examine.com/supplements/oxytropis-falcate/",
    "https://examine.com/supplements/paederia-foetida/",
    "https://examine.com/supplements/palmatine/",
    "https://examine.com/supplements/panax-ginseng/",
    "https://examine.com/supplements/patchouli/",
    "https://examine.com/supplements/paullinia-cupana/",
    "https://examine.com/supplements/pedalium-murex/",
    "https://examine.com/supplements/pelargonidin/",
    "https://examine.com/supplements/pelargonium-sidoides/",
    "https://examine.com/supplements/peppermint/",
    "https://examine.com/supplements/perilla-oil/",
    "https://examine.com/supplements/phellodendron-amurense/",
    "https://examine.com/supplements/phenylethylamine/",
    "https://examine.com/supplements/phenylpiracetam/",
    "https://examine.com/supplements/phosphatidylcholine/",
    "https://examine.com/supplements/phosphatidylserine/",
    "https://examine.com/supplements/piceatannol/",
    "https://examine.com/supplements/picrorhiza-kurroa/",
    "https://examine.com/supplements/pine-pollen/",
    "https://examine.com/supplements/piracetam/",
    "https://examine.com/supplements/policosanol/",
    "https://examine.com/supplements/polygala-tenuifolia/",
    "https://examine.com/supplements/polypodium-leucotomos/",
    "https://examine.com/supplements/pomegranate/",
    "https://examine.com/supplements/potassium/",
    "https://examine.com/supplements/pramiracetam/",
    "https://examine.com/supplements/prickly-pear-fruit/",
    "https://examine.com/supplements/prl-8-53/",
    "https://examine.com/supplements/psoralea-corylifolia/",
    "https://examine.com/supplements/psyllium/",
    "https://examine.com/supplements/pterostilbene/",
    "https://examine.com/supplements/pueraria-lobata/",
    "https://examine.com/supplements/pueraria-mirifica/",
    "https://examine.com/supplements/punicalagins/",
    "https://examine.com/supplements/punicic-acid/",
    "https://examine.com/supplements/pycnogenol/",
    "https://examine.com/supplements/pygeum/",
    "https://examine.com/supplements/pyritinol/",
    "https://examine.com/supplements/pyrroloquinoline-quinone/",
    "https://examine.com/supplements/pyruvate/",
    "https://examine.com/supplements/quercetin/",
    "https://examine.com/supplements/raspberry-ketone/",
    "https://examine.com/supplements/rauwolscine/",
    "https://examine.com/supplements/red-clover-extract/",
    "https://examine.com/supplements/red-yeast-rice/",
    "https://examine.com/supplements/resveratrol/",
    "https://examine.com/supplements/rhamnus-nakaharai/",
    "https://examine.com/supplements/rhaponticum-carthamoides/",
    "https://examine.com/supplements/rhodiola-rosea/",
    "https://examine.com/supplements/rooibos/",
    "https://examine.com/supplements/rose-essential-oil/",
    "https://examine.com/supplements/rose-hip/",
    "https://examine.com/supplements/rosmarinic-acid/",
    "https://examine.com/supplements/royal-jelly/",
    "https://examine.com/supplements/rubus-coreanus/",
    "https://examine.com/supplements/rubus-suavissimus/",
    "https://examine.com/supplements/ruscus-aculeatus/",
    "https://examine.com/supplements/s-adenosyl-methionine/",
    "https://examine.com/supplements/safflower-oil/",
    "https://examine.com/supplements/saffron/",
    "https://examine.com/supplements/salacia-reticulata/",
    "https://examine.com/supplements/salvia-hispanica/",
    "https://examine.com/supplements/salvia-miltiorrhiza/",
    "https://examine.com/supplements/salvia-sclarea/",
    "https://examine.com/supplements/sarcosine/",
    "https://examine.com/supplements/saw-palmetto/",
    "https://examine.com/supplements/sceletium-tortuosum/",
    "https://examine.com/supplements/schisandra-chinensis/",
    "https://examine.com/supplements/schizonepeta-tenuifolia/",
    "https://examine.com/supplements/scutellaria-baicalensis/",
    "https://examine.com/supplements/sea-buckthorn/",
    "https://examine.com/supplements/selenium/",
    "https://examine.com/supplements/senna-alexandrina/",
    "https://examine.com/supplements/serrapeptase/",
    "https://examine.com/supplements/sesamin/",
    "https://examine.com/supplements/shilajit/",
    "https://examine.com/supplements/silica/",
    "https://examine.com/supplements/silk-amino-acids/",
    "https://examine.com/supplements/simmondsia-chinensis/",
    "https://examine.com/supplements/sodium-bicarbonate/",
    "https://examine.com/supplements/sophora-flavescens/",
    "https://examine.com/supplements/soy-isoflavones/",
    "https://examine.com/supplements/soy-lecithin/",
    "https://examine.com/supplements/sphaeranthus-indicus/",
    "https://examine.com/supplements/spilanthes-acmella/",
    "https://examine.com/supplements/spirulina/",
    "https://examine.com/supplements/squalene/",
    "https://examine.com/supplements/stephania-tetrandra/",
    "https://examine.com/supplements/stevia/",
    "https://examine.com/supplements/stinging-nettle/",
    "https://examine.com/supplements/sulbutiamine/",
    "https://examine.com/supplements/sulforaphane/",
    "https://examine.com/supplements/sunifiram/",
    "https://examine.com/supplements/synephrine/",
    "https://examine.com/supplements/syzygium-aromaticum/",
    "https://examine.com/supplements/t3/",
    "https://examine.com/supplements/taraxacum-officinale/",
    "https://examine.com/supplements/taurine/",
    "https://examine.com/supplements/tauroursodeoxycholic-acid/",
    "https://examine.com/supplements/tea-camellia-sinensis/",
    "https://examine.com/supplements/terminalia-arjuna/",
    "https://examine.com/supplements/tetradecyl-thioacetic-acid/",
    "https://examine.com/supplements/theacrine/",
    "https://examine.com/supplements/theaflavins/",
    "https://examine.com/supplements/theanine/",
    "https://examine.com/supplements/tinospora-cordifolia/",
    "https://examine.com/supplements/traditional-chinese-medicine/",
    "https://examine.com/supplements/trametes-versicolor/",
    "https://examine.com/supplements/trehalose/",
    "https://examine.com/supplements/tribulus-terrestris/",
    "https://examine.com/supplements/trichopus-zeylanicus/",
    "https://examine.com/supplements/trimethylglycine/",
    "https://examine.com/supplements/tripterygium-wilfordii/",
    "https://examine.com/supplements/tulbaghia-violacea/",
    "https://examine.com/supplements/turmeric/",
    "https://examine.com/supplements/type-ii-collagen/",
    "https://examine.com/supplements/uncaria-rhynchophylla/",
    "https://examine.com/supplements/uncaria-tomentosa/",
    "https://examine.com/supplements/uridine/",
    "https://examine.com/supplements/ursolic-acid/",
    "https://examine.com/supplements/uva-ursi/",
    "https://examine.com/supplements/valeriana-officinalis/",
    "https://examine.com/supplements/valine/",
    "https://examine.com/supplements/vanadium/",
    "https://examine.com/supplements/vegan/",
    "https://examine.com/supplements/velvet-antler/",
    "https://examine.com/supplements/vinpocetine/",
    "https://examine.com/supplements/vitamin-a/",
    "https://examine.com/supplements/vitamin-b1/",
    "https://examine.com/supplements/vitamin-b12/",
    "https://examine.com/supplements/vitamin-b2/",
    "https://examine.com/supplements/vitamin-b3/",
    "https://examine.com/supplements/vitamin-b5/",
    "https://examine.com/supplements/vitamin-b6/",
    "https://examine.com/supplements/vitamin-c/",
    "https://examine.com/supplements/vitamin-d/",
    "https://examine.com/supplements/vitamin-e/",
    "https://examine.com/supplements/vitamin-k/",
    "https://examine.com/supplements/vitex-agnus-castus/",
    "https://examine.com/supplements/watercress/",
    "https://examine.com/supplements/whey-protein/",
    "https://examine.com/supplements/white-kidney-bean-extract/",
    "https://examine.com/supplements/wine/",
    "https://examine.com/supplements/yacon/",
    "https://examine.com/supplements/yamabushitake/",
    "https://examine.com/supplements/yerba-mate/",
    "https://examine.com/supplements/yohimbine/",
    "https://examine.com/supplements/zeaxanthin/",
    "https://examine.com/supplements/zinc/",
    "https://examine.com/supplements/ziziphus-jujuba/",
    "https://examine.com/supplements/zma/",
]

# pip3 install spacy
# python3 -m spacy download en_core_web_sm
nlp = spacy.load("en_core_web_sm")


for supp in SUPPLEMENTS:
    print("searching: " + supp)
    response = requests.get(supp)
    soup = BeautifulSoup(response.content, "lxml")
    result_text = StringIO(newline="\n")
    content = soup.find_all("div", {"class": "th-module-content"})
    for item in content:
        para = item.find_all("p")
        for p in para:
            t = p.getText(strip=True)
            if "Click" in t:
                t = ""
            else:
                doc = nlp(t)
                for token in doc.sents:
                    sent_bool = False
                    for tok in token:
                        if "[" in tok.text or "]" in tok.text:
                            sent_bool = True
                    if sent_bool == False:
                        result_text.write(token.text)
                    else:
                        for tok in token:
                            if "[" in tok.text or "]" in tok.text:
                                continue
                            result_text.write(tok.text + " ")

            result_text.write("   ##~~##~~##~~##~~##~~##~~##   ")

    file_name = supp.rsplit("/")[-2]
    result_text = result_text.getvalue()
    result_text = result_text.replace("\\n", "")
    with open(file_name, "w") as out_file:
        out_file.write(json.dumps({supp: result_text}, sort_keys=True))
